apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensor-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sensor-service
                port:
                  number: 84
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-service
spec:
  selector:
    app: sensor-app
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-app
  template:
    metadata:
      labels:
        app: sensor-app
    spec:
      containers:
        - name: sensor-container
          image: sgal88/sgalk3s:1.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8084
          volumeMounts:
            - mountPath: /dev/mem
              name: mem
            - mountPath: /dev/gpiomem
              name: gpiomem
      volumes:
        - name: mem
          hostPath:
            path: /dev/mem
        - name: gpiomem
          hostPath:
            path: /dev/gpiomem
